create database sample1;
use sample1;

### TOPIC ONE - CREATING THE TABLES  AND ALTER THE TABLES


## Pre-requirement - Please watch the Data types video and DLL videos for the below questions.

/*
Creating a table that consists of numerical columns 
*/

create table emp_person_details 
(
id INT,
name varchar(30),
gender CHAR(10),
age TINYINT,
family_strength BIT(15),
marital_status BOOL,
dob DATE
);

# TABLE NUMBER TWO I.E PROFESSIONAL DETAILS

CREATE TABLE emp_professional_details
(
ID INT, # or we can also use other data types like int or(integer), smallint, bigint.
DOJ DATE,
ANNUAL_PAY REAL(20,3),
PROBATION_COMPLETED boolean,
DESIGNATION CHAR(20), # YOU CAN USE OTHER DATATYPES ASWELL LIKE VARCHAR, TEXT, ETC
PREVIOUS_DESIGNATION TEXT,
PREVIOUS_YR_EXP TINYINT
);


# TABLE NUMBER THREE I.E PAYSLIP DETAILS

CREATE TABLE EMP_PAYSLIP_DETAILS
(
ID INT,
DATE_OF_SLIP_GENERATED TIMESTAMP
);

## MODIFICATION TO THE TABLES:

/*
Let's set the constraints to the columns:
*/

### BEFORE DOING ANY CHANGES, LET'S CEHCK THE DESCRIPTION:

DESC emp_person_details;
DESC emp_professional_details;
DESC EMP_PAYSLIP_DETAILS;

## Altering the constraints of the table

## ADDING THE PRMIARY KEY
ALTER TABLE emp_person_details
ADD primary key(ID);

## FOREIGN KEY EMPLOYEE_PROFESSIONAL_DETAILS
ALTER TABLE emp_professional_details
ADD CONSTRAINT FK_EPD FOREIGN KEY (ID) REFERENCES emp_person_details(ID);


### ADDING PRIMARY KEY TO THE EMPLOYEE_PROFESSIONAL_DETAILS

ALTER TABLE emp_professional_details
ADD PRIMARY KEY(ID);

### ADDING FOREING KEY FOR THE EMP_PAYSLIP_DETAILS

ALTER TABLE EMP_PAYSLIP_DETAILS
ADD CONSTRAINT FK_EPD1 FOREIGN KEY (ID) REFERENCES emp_person_details(ID);

ALTER TABLE EMP_PAYSLIP_DETAILS
ADD CONSTRAINT FK_EPD2 FOREIGN KEY (ID) REFERENCES emp_professional_details(ID);

## ADDING CHECK CONSTAINTS:

ALTER TABLE emp_person_details
ADD CONSTRAINT CHK_CON1 CHECK (AGE>18);

## ADDING CONSTRAINTS LIKE NOT NULL AND UNIQUE
ALTER TABLE emp_person_details
MODIFY COLUMN NAME VARCHAR(30) NOT NULL UNIQUE;



### Altering the attributes of the tables


## ADDING THE NEW COLUMN CALLED MONTHY SALARY

ALTER TABLE EMP_PAYSLIP_DETAILS
ADD MONTHLY_SALARY DECIMAL(12,2);

/*
OR ALSO WE CAN ADD THE COLUMN AFTER ID USING THE AFTER COMMAND AS WELL AS WE CAN ADD IT AS A FIRST COLUMN USING THE FIRST KEYWORD

## ADDING THE COLUMN SALARY AFTER THE EMP_ID IN EMP_PAYSLIP_DETAILS

ALTER TABLE EMP_PAYSLIP_DETAILS
ADD MONTHLY_SALARY DECIMAL(12,2) AFTER EMP_ID;

*/

## RENAME COMMAND

# Let's change the name for DATE_OF_PAYSLIP_GEN column

ALTER TABLE EMP_PAYSLIP_DETAILS
RENAME  COLUMN DATE_OF_PAYSLIP_GEN  TO DATE_OF_MONTH_PAYSLIP_GEN;


## Let's see how to drop the column.

# Let's add one column to the EMP_PAYSLIP_DETAILS variable
alter table EMP_PAYSLIP_DETAILS
add Transaction_id integer(30);

# let's see the structure of the table
desc EMP_PAYSLIP_DETAILS;

## Let's drop it now

alter table EMP_PAYSLIP_DETAILS
drop Transaction_id;


 ## LET'S CHECK THE STRUCTURE OF THE EMP_PAYSLIP_DETAILS TABLE.
 
 DESC EMP_PAYSLIP_DETAILS;


